[package]
name = "bepuvy-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# [lib]
# crate-type = ["cdylib"]

[lib]
crate-type = ["rlib"]

[build_dependencies]
which = "*"
bindgen = "0.65.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
