
#For some REALLY REALLY stupid reason we have to use the MacOS ld because
#The shipped LD/mold does not treat -lc++ the same.
# [target.aarch64-apple-darwin]
# rustflags = [
#     "-C", 
#     "link-arg=-fuse-ld=/Library/Developer/CommandLineTools/usr/bin/ld",
#     "-Zshare-generics=y",
# ]

# [debug]
# level = "limited"


# [target.aarch64-apple-darwin]
# rustflags = [
#     "-C", 
#     "link-arg=-fuse-ld=/Users/drewridley/Documents/sold/build/ld64",
#     "-Zshare-generics=y",
# ]
